name: histoTIL
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudnn=8.1.0
  - cudatoolkit=11.2
  - python-utils
  - opencv
  - pillow
  - scikit-image
  - spyder-kernels=2.3
  - pandas
  -pip:
   - dill==0.3.3
   - openslide-python==1.1.2
   - importlib-resources
   - openslide-python==1.1.2
   - scikit-learn==0.24.1
   - scikit-image==0.18.1
   - install scipy==1.6.1
