function feat_extraction_wsi(folder_matpatches,folder_pyepistroma,folder_matcellmask,folder_savepath,quality,folder_type)
% counter for process at least 20 tiles
z_val = 1.96;
p_val = 0.5;
e_val = 0.05;
b = (z_val^2)*(p_val*(1-p_val));
c = e_val^2;
a = b/c;
e = (z_val^2)*p_val*(1-p_val);
lympModel=load('C:\Users\cbarr23\Documents\HistoTIL\libs\lymp_svm_matlab_wsi.mat');
%lympModel=load('/home/maberyick/CCIPD_Research/Github/HistoTIL/libs/lymp_svm_matlab_wsi.mat');
lympModel = lympModel.model;
placeholder = 'placeholder';
% determine if single tiles (case) or folder (multiple cases)
if folder_type == "tile_type"
    imgList=dir([folder_matpatches '*.png']);
    indx = randperm(numel(imgList));
    numFiles=length(imgList);
    imgList = {imgList(:).name};
    imgList = parallel.pool.Constant(imgList);
    qualitysaturationLim = quality.saturationLim;
    qualityredChannelLim = quality.redChannelLim;
    qualityblurLimit = quality.blurLimit;
    qualityimgarea = quality.imgarea;
    fprintf('\n');
    dispstat('','init'); % One time only initialization
    dispstat(sprintf('Begining the process...'),'keepthis','timestamp'); 
    %textprogressbar('calculating histoTIL features...');fprintf('\n');
    parfor nn=1:numFiles
        perct = 100*nn/numFiles;
        %textprogressbar(perct);
        dispstat(sprintf('Progress %d%%',perct),'timestamp'); 
        i= indx(nn);
        [~,imgName]=fileparts(imgList.Value{i});
        outputFolder=[folder_savepath 'dataset_output/' imgName];
        maskFolder=[outputFolder '/png_binmask/png_cellmask/'];
        maskEFolder=[outputFolder '/png_binmask/png_cellepimask/'];
        maskSFolder=[outputFolder '/png_binmask/png_cellstromask/'];
        maskBFolder=[outputFolder '/png_binmask/png_cellbundmask/'];
        ESmaskFolder=[outputFolder '/png_binmask/png_epithmask/'];
        SSmaskFolder=[outputFolder '/png_binmask/png_stromask/'];
        EBmaskFolder=[outputFolder '/png_binmask/png_boundaryepistromask/'];
        featlocFolder=[outputFolder '/TIL_features/'];
        %disp(outputFolder)
        [~,~] = mkdir(outputFolder);
        [~,~] = mkdir(maskFolder);
        [~,~] = mkdir(maskEFolder);
        [~,~] = mkdir(maskSFolder);
        [~,~] = mkdir(maskBFolder);
        [~,~] = mkdir(ESmaskFolder);
        [~,~] = mkdir(SSmaskFolder);
        [~,~] = mkdir(EBmaskFolder);
        [~,~] = mkdir(featlocFolder);
        featFile=sprintf('%s/%s.mat',featlocFolder,imgName);
        maskFile=sprintf('%s/%s.png',maskFolder,imgName);
        maskEFile=sprintf('%s/%s.png',maskEFolder,imgName);
        maskSFile=sprintf('%s/%s.png',maskSFolder,imgName);
        maskBFile=sprintf('%s/%s.png',maskBFolder,imgName);
        ESmaskFile=sprintf('%s/%s.png',ESmaskFolder,imgName);
        SSmaskFile=sprintf('%s/%s.png',SSmaskFolder,imgName);
        EBmaskFile=sprintf('%s/%s.png',EBmaskFolder,imgName);
        % load the image
        curTile = imread([folder_matpatches imgList.Value{i}]);
        [ima,imb,~] = size(curTile);
        % load the epistroma mask
        curTile_ESmask = imread([folder_pyepistroma imgList.Value{i}]);
        [ms1a,~,~] = size(curTile_ESmask);  
        % load the nuclei mask, if not saved, calculate
        curTile_Nmask = imread([folder_matcellmask imgList.Value{i}]);
        [ms2a,~,~] = size(curTile_Nmask);  
        % check for size
        if ima ~= ms1a
            curTile_ESmask = imresize(curTile_ESmask,[ima imb]);
        end
        if ima ~= ms2a
            curTile_Nmask = imresize(curTile_Nmask,[ima imb]);
        end
        % get_cleanMask_v2
        %get_cleanMask_v2(I,M,maskFile);

        % generate the nuclei mask
        if (getSaturationMetric(curTile)>qualitysaturationLim && ...
                getRedMetric(curTile)>qualityredChannelLim && ...
                blurMetric(curTile)>qualityblurLimit && ...
                getAreaTissue(curTile)>qualityimgarea)
            if exist(featFile,'file')~=2
                parsave(featFile, placeholder);
                % Check if Cell mask and Epistroma mask have same quantity
                if size(curTile_ESmask) == size(curTile_Nmask)
                    %fprintf('Processing tile %s_%d\n',imgName,i);
                    [nucleiCentroids,isLymphocyte,nucFeatures,denFeat,spaFeat,ctxFeat,spaFeat_v2,perinuclear,nucleiCentroids_stro,...
                        isLymphocyte_stro,nucFeatures_stro,denFeat_stro,spaFeat_stro,ctxFeat_stro,spaFeat_v2_stro,perinuclear_stro,nucleiCentroids_epi,isLymphocyte_epi,...
                        nucFeatures_epi,denFeat_epi,spaFeat_epi,ctxFeat_epi,spaFeat_v2_epi,perinuclear_epi,nucleiCentroids_bund,isLymphocyte_bund,nucFeatures_bund,...
                        denFeat_bund,spaFeat_bund,ctxFeat_bund,spaFeat_v2_bund,perinuclear_bund] = get_mixTIL(...
                        curTile,curTile_ESmask,curTile_Nmask,maskFile,maskEFile,...
                        maskSFile,maskBFile,ESmaskFile,SSmaskFile,EBmaskFile,lympModel);
                    parsave_cellfeat_mixtil(featFile,nucleiCentroids,isLymphocyte,nucFeatures,denFeat,spaFeat,ctxFeat,spaFeat_v2,perinuclear,nucleiCentroids_stro,...
                        isLymphocyte_stro,nucFeatures_stro,denFeat_stro,spaFeat_stro,ctxFeat_stro,spaFeat_v2_stro,perinuclear_stro,nucleiCentroids_epi,isLymphocyte_epi,...
                        nucFeatures_epi,denFeat_epi,spaFeat_epi,ctxFeat_epi,spaFeat_v2_epi,perinuclear_epi,nucleiCentroids_bund,isLymphocyte_bund,nucFeatures_bund,...
                        denFeat_bund,spaFeat_bund,ctxFeat_bund,spaFeat_v2_bund,perinuclear_bund);
                else
                    filePh_error = fopen([folder_savepath 'errorlist_patches.txt'],'a');
                    %fprintf(filePh_error,'Mismatch cell and epistroma mask %s_%d\n',imgName,indx2(i));
                    fclose(filePh_error);
                    continue
                end
            else
                %disp('mat tile already exists')
                continue
            end
        end
    end
elseif folder_type == "folder_type"
    folderList = dir(folder_matpatches);
    folderNames = {folderList([folderList.isdir]).name};
    folderNames = folderNames(~ismember(folderNames ,{'.','..'}));
    fprintf('\n');
    dispstat('','init'); % One time only initialization
    dispstat(sprintf('Begining the process...'),'keepthis','timestamp'); 
    %textprogressbar('calculating histoTIL features...');fprintf('\n');
    for mm=1:length(folderNames)
        perct = 100*mm/length(folderNames);
        %textprogressbar(perct);
        dispstat(sprintf('Progress %d%%',perct),'timestamp'); 
        folderName = folderNames{mm};
        imgList=dir([folder_matpatches folderName filesep '*.png']);
        indx = randperm(numel(imgList));
        numFiles=length(imgList);
        imgList = {imgList(:).name};
        imgList = parallel.pool.Constant(imgList);
        qualitysaturationLim = quality.saturationLim;
        qualityredChannelLim = quality.redChannelLim;
        qualityblurLimit = quality.blurLimit;
        qualityimgarea = quality.imgarea;
        % once feature extraction is improved, used this to account for the
        % number of samples needed per image
        f = numFiles*e_val^2;
        d = 1+e/f;
        sample_size = round(a/d);
        % counter for process at least 28 tiles if higher than 30
        %if sample_size > 30
        %    sample_size = 28;
        %end
        parfor nn=1:sample_size
            i= indx(nn);
            [~,imgName]=fileparts(imgList.Value{i});
            outputFolder=[folder_savepath 'dataset_output' filesep folderName];
            maskFolder=[outputFolder filesep 'png_binmask' filesep 'png_cellmask'];
            maskEFolder=[outputFolder filesep 'png_binmask' filesep 'png_cellepimask'];
            maskSFolder=[outputFolder filesep 'png_binmask' filesep 'png_cellstromask'];
            maskBFolder=[outputFolder filesep 'png_binmask' filesep 'png_cellbundmask'];
            ESmaskFolder=[outputFolder filesep 'png_binmask' filesep 'png_epithmask'];
            SSmaskFolder=[outputFolder filesep 'png_binmask' filesep 'png_stromask'];
            EBmaskFolder=[outputFolder filesep 'png_binmask' filesep 'png_boundaryepistromask'];
            featlocFolder=[outputFolder filesep 'TIL_features'];
            % if image has already the patches, then skip to next case
            file_count = dir([featlocFolder filesep '*.mat']);
            file_count = numel(file_count);
            if file_count > sample_size-1
                continue
            end
            %disp(outputFolder)
            [~,~] = mkdir(outputFolder);
            [~,~] = mkdir(maskFolder);
            [~,~] = mkdir(maskEFolder);
            [~,~] = mkdir(maskSFolder);
            [~,~] = mkdir(maskBFolder);
            [~,~] = mkdir(ESmaskFolder);
            [~,~] = mkdir(SSmaskFolder);
            [~,~] = mkdir(EBmaskFolder);
            [~,~] = mkdir(featlocFolder);
            featFile=sprintf('%s/%s.mat',featlocFolder,imgName);
            maskFile=sprintf('%s/%s.png',maskFolder,imgName);
            maskEFile=sprintf('%s/%s.png',maskEFolder,imgName);
            maskSFile=sprintf('%s/%s.png',maskSFolder,imgName);
            maskBFile=sprintf('%s/%s.png',maskBFolder,imgName);
            ESmaskFile=sprintf('%s/%s.png',ESmaskFolder,imgName);
            SSmaskFile=sprintf('%s/%s.png',SSmaskFolder,imgName);
            EBmaskFile=sprintf('%s/%s.png',EBmaskFolder,imgName);
            % load the image
            curTile = imread([folder_matpatches folderName filesep imgList.Value{i}]);
            [ima,imb,~] = size(curTile);
            % load the epistroma mask
            curTile_ESmask = imread([folder_pyepistroma folderName filesep imgList.Value{i}]);
            [ms1a,~,~] = size(curTile_ESmask);
            % load the nuclei mask, if not saved, calculate
            curTile_Nmask = imread([folder_matcellmask folderName filesep imgList.Value{i}]);
            [ms2a,~,~] = size(curTile_Nmask);
            % check for size
            if ima ~= ms1a
                curTile_ESmask = imresize(curTile_ESmask,[ima imb]);
            end
            if ima ~= ms2a
                curTile_Nmask = imresize(curTile_Nmask,[ima imb]);
            end
            % generate the nuclei mask
            if (getSaturationMetric(curTile)>qualitysaturationLim && ...
                    getRedMetric(curTile)>qualityredChannelLim && ...
                    blurMetric(curTile)>qualityblurLimit && ...
                    getAreaTissue(curTile)>qualityimgarea)
                if exist(featFile,'file')~=2
                    parsave(featFile, placeholder);
                    % Check if Cell mask and Epistroma mask have same quantity
                    %                     if size(curTile_ESmask) == size(curTile_Nmask)
                    %fprintf('Processing tile %s_%d\n',imgName,i);
                    [nucleiCentroids,isLymphocyte,nucFeatures,denFeat,spaFeat,ctxFeat,spaFeat_v2,perinuclear,nucleiCentroids_stro,...
                        isLymphocyte_stro,nucFeatures_stro,denFeat_stro,spaFeat_stro,ctxFeat_stro,spaFeat_v2_stro,perinuclear_stro,nucleiCentroids_epi,isLymphocyte_epi,...
                        nucFeatures_epi,denFeat_epi,spaFeat_epi,ctxFeat_epi,spaFeat_v2_epi,perinuclear_epi,nucleiCentroids_bund,isLymphocyte_bund,nucFeatures_bund,...
                        denFeat_bund,spaFeat_bund,ctxFeat_bund,spaFeat_v2_bund,perinuclear_bund] = get_mixTIL(...
                        curTile,curTile_ESmask,curTile_Nmask,maskFile,maskEFile,...
                        maskSFile,maskBFile,ESmaskFile,SSmaskFile,EBmaskFile,lympModel);
                    parsave_cellfeat_mixtil(featFile,nucleiCentroids,isLymphocyte,nucFeatures,denFeat,spaFeat,ctxFeat,spaFeat_v2,perinuclear,nucleiCentroids_stro,...
                        isLymphocyte_stro,nucFeatures_stro,denFeat_stro,spaFeat_stro,ctxFeat_stro,spaFeat_v2_stro,perinuclear_stro,nucleiCentroids_epi,isLymphocyte_epi,...
                        nucFeatures_epi,denFeat_epi,spaFeat_epi,ctxFeat_epi,spaFeat_v2_epi,perinuclear_epi,nucleiCentroids_bund,isLymphocyte_bund,nucFeatures_bund,...
                        denFeat_bund,spaFeat_bund,ctxFeat_bund,spaFeat_v2_bund,perinuclear_bund);
                    %                     else
                    %                         filePh_error = fopen([folder_savepath 'errorlist_patches.txt'],'a');
                    %                         fprintf(filePh_error,'Mismatch cell and epistroma mask %s_%d\n',imgName,indx2(i));
                    %                         fclose(filePh_error);
                    %                         continue
                    %                     end
                else
                    %disp('mat tile already exists')
                    continue
                end
            end
        end
    end
else
    %disp('no fodler type')
end
dispstat('Finished.','keepprev'); 
fprintf('\n')
fprintf('all done');
%ToDo: include method to delete the 1Kb files
% parfor n=1:numFiles
%     [~,imgName]=fileparts(imgList.Value{n});
%     % ToDo: Check if the nuclei and ES are already being processed, to be
%     % used with another feature set
%     %imgFile=[folder_matpatches imgList{n}];
%     outputFolder=[folder_savepath 'dataset_output/' imgName];
%     featlocFolder=[outputFolder '/TIL_features/*.mat'];
%     files = dir(featlocFolder);
%     for ii = 1:length(files)
%         if files(ii).bytes==187 % file with 'placeholder' word
%             delete(fullfile(files(ii).folder, files(ii).name))
%         end
%     end
% end
% Save the geenral feature description
 description_spaTIL = {'avg of ratio of the nuceli cluster density to its closest lym cluster cluster',...
    'avg of ratio of the nuceli cluster density to its second closest lym cluster density',...
    'avg of ratio of the nuceli cluster density to its third closest lym cluster density',...
    'avg of ratio of the nuceli cluster density to its first three closest lym cluster mean density',...
    'std of ratio of the nuceli cluster density to its closest lym cluster cluster',...
    'std of ratio of the nuceli cluster density to its second closest lym cluster density',...
    'std of ratio of the nuceli cluster density to its third closest lym cluster density',...
    'std of ratio of the nuceli cluster density to its first three closest lym cluster mean density',...
    'var of ratio of the nuceli cluster density to its closest lym cluster cluster',...
    'var of ratio of the nuceli cluster density to its second closest lym cluster density',...
    'var of ratio of the nuceli cluster density to its third closest lym cluster density',...
    'var of ratio of the nuceli cluster density to its first three closest lym cluster mean density',...
    'min of ratio of the nuceli cluster density to its closest lym cluster cluster',...
    'min of ratio of the nuceli cluster density to its second closest lym cluster density',...
    'min of ratio of the nuceli cluster density to its third closest lym cluster density',...
    'min of ratio of the nuceli cluster density to its first three closest lym cluster mean density',...
    'max of ratio of the nuceli cluster density to its closest lym cluster cluster',...
    'max of ratio of the nuceli cluster density to its second closest lym cluster density',...
    'max of ratio of the nuceli cluster density to its third closest lym cluster density',...
    'max of ratio of the nuceli cluster density to its first three closest lym cluster mean density',...
    'range of ratio of the nuceli cluster density to its closest lym cluster cluster',...
    'range of ratio of the nuceli cluster density to its second closest lym cluster density',...
    'range of ratio of the nuceli cluster density to its third closest lym cluster density',...
    'range of ratio of the nuceli cluster density to its first three closest lym cluster mean density',...
    'avg of reciprocal of number of least lym cluster to encompass nuclei cluster'...
    'std of reciprocal of number of least lym cluster to encompass nuclei cluster'...
    'var of reciprocal of number of least lym cluster to encompass nuclei cluster'...
    'min of reciprocal of number of least lym cluster to encompass nuclei cluster'...
    'max of reciprocal of number of least lym cluster to encompass nuclei cluster'...
    'range of reciprocal of number of least lym cluster to encompass nuclei cluster',...
    'avg of area ratio of nuclei cluster to encompassed lym clusters'...
    'std of area ratio of nuclei cluster to encompassed lym clusters'...
    'var of area ratio of nuclei cluster to encompassed lym clusters'...
    'min of area ratio of nuclei cluster to encompassed lym clusters'...
    'max of area ratio of nuclei cluster to encompassed lym clusters'...
    'range of area ratio of nuclei cluster to encompassed lym clusters'...
    'avg of density ratio of nuclei cluster to encompassed lym clusters'...
    'std of density ratio of nuclei cluster to encompassed lym clusters'...
    'var of density ratio of nuclei cluster to encompassed lym clusters'...
    'min of density ratio of nuclei cluster to encompassed lym clusters'...
    'max of density ratio of nuclei cluster to encompassed lym clusters'...
    'range of density ratio of nuclei cluster to encompassed lym clusters',...
    '1-norm of the vector by ratio of nucleiDegree to LymDegree'...
    '1-norm of the vector by ratio of nucleiCloseness to LymCloseness'...
    '1-norm of the vector by nucleiBetweenness minus LymBetweenness'...
    '1-norm of the vector by ratio of nucleiEigenvector to LymEigenvector'...
    '1-norm of the vector by ratio of nucleiSumIndex to LymSumIndex'...
    'ratio of number of unique lym nodes to all lym nodes'...
    'average distance of nuclei to nearest lym',...
    'lympTotArea','lymAvgArea','lymMedianArea','lymStdArea',...
    'lymModeArea','nonLympTotArea','nonLymAvgArea','nonLymMedianArea',...
    'nonLymStdArea','nonLymModeArea',...
    'lympTotDensity','lymAvgDensity','lymMedianDensity',...
    'lymStdDensity','lymModeDensity','nonLympTotDensity','nonLymAvgDensity',...
    'nonLymMedianDensity','nonLymStdDensity','nonLymModeDensity',...
    'intersectedArea',...
    'avg_1_nearest','median_1_nearest','mode_1_nearest',...
    'avg_2_nearest','median_2_nearest','mode_2_nearest',...
    'avg_3_nearest','median_1_nearest','mode_3_nearest',...
    'avg_4_nearest','median_1_nearest','mode_4_nearest',...
    'avg_5_nearest','median_1_nearest','mode_5_nearest'};
zernFeats=zeros(1,36*2);
numZernikePol=size(zernFeats,2)/2; zernNames={};
for i=1:numZernikePol
    num=num2str(i);
    zernNames=[zernNames, ['ZernPol' num '_A'], ['ZernPol' num '_Phi']];
end
harNames={'AngularSecondMoment','Contrast','Correlation',...
    'Variance','Homogeneity','SumAverage','SumVariance','SumEntropy',...
    'Entropy','DifferenceVariance','DifferenceEntropy','InfoMeasureCorrI',...
    'InfoMeasureCorrII','MaxCorrCoeff'};
description_nucFeat=[{'Area','Eccentricity','RatioAxes','MedianRed','EntropyRed',...
    'MinIntensity','MaxIntensity','EquivDiameter','Orientation',...
    'EntropyIntensity','MedianIntensity','EdgeMeanIntensity','RatioMedianRedBlue',...
    'RatioMedianRedGreen'},harNames,zernNames];
description_denTIL ={'#Lymp/TissueArea','LympTotalArea/TissueArea',...
        '#Lymp/#TotalNuclei','MaxLympGroupingFactor','MinLympGroupingFactor',...
        'AvgLympGroupingFactor','StdLympGroupingFactor',...
        'MedianLympGroupingFactor','ModeLympGroupingFactor','NumHighlyGroupedLymp',...
        '#Lymp/TotalConvHullArea','LympConvHullArea/TotalConvHullArea',...
        'IntersectedAreaConvHullLymp&NonLymp','MaxDensityMatrixVal',...
        'MinDensityMatrixVal','AvgDensityMatrixVal','StdDensityMatrixVal',...
        'MedianDensityMatrixVal','ModeDensityMatrixVal',...       
        };
description_ctxTIL = {'filtquantvarmatK1','filtquantvarmatK2','filtquantvarmatK3','filtareasvarmatK1',...
    'filtareasvarmatK2','filtareasvarmatK3','filtareasmeanmatK1','filtareasmeanmatK2','filtareasmeanmatK3',...
    'filtareasmedianmatK1','filtareasmedianmatK2','filtareasmedianmatK3','filtareasstdmatK1','filtareasstdmatK2',...
    'filtareasstdmatK3','filteccentricityvarmatK1','filteccentricityvarmatK2','filteccentricityvarmatK3',...
    'filteccentricitymeanmatK1','filteccentricitymeanmatK2','filteccentricitymeanmatK3','filteccentricitymedianmatK1',...
    'filteccentricitymedianmatK2','filteccentricitymedianmatK3','filteccentricitystdmatK1','filteccentricitystdmatK2',...
    'filteccentricitystdmatK3','filtdiametervarmatK1','filtdiametervarmatK2','filtdiametervarmatK3',...
    'filtdiametermeanmatK1','filtdiametermeanmatK2','filtdiametermeanmatK3','filtdiametermedianmatK1',...
    'filtdiametermedianmatK2','filtdiametermedianmatK3','filtdiameterstdmatK1','filtdiameterstdmatK2',...
    'filtdiameterstdmatK3','filtmeanIntensityvarmatK1','filtmeanIntensityvarmatK2','filtmeanIntensityvarmatK3',...
    'filtmeanIntensitymeanmatK1','filtmeanIntensitymeanmatK2','filtmeanIntensitymeanmatK3',...
    'filtmeanIntensitymedianmatK1','filtmeanIntensitymedianmatK2','filtmeanIntensitymedianmatK3',...
    'filtmeanIntensitystdmatK1','filtmeanIntensitystdmatK2','filtmeanIntensitystdmatK3','filtentropyRedvarmatK1',...
    'filtentropyRedvarmatK2','filtentropyRedvarmatK3','filtentropyRedmeanmatK1','filtentropyRedmeanmatK2',...
    'filtentropyRedmeanmatK3','filtentropyRedmedianmatK1','filtentropyRedmedianmatK2','filtentropyRedmedianmatK3',...
    'filtentropyRedstdmatK1','filtentropyRedstdmatK2','filtentropyRedstdmatK3','filtratioRedBbluevarmatK1',...
    'filtratioRedBbluevarmatK2','filtratioRedBbluevarmatK3','filtratioRedBbluemeanmatK1','filtratioRedBbluemeanmatK2',...
    'filtratioRedBbluemeanmatK3','filtratioRedBbluemedianmatK1','filtratioRedBbluemedianmatK2',...
    'filtratioRedBbluemedianmatK3','filtratioRedBbluestdmatK1','filtratioRedBbluestdmatK2','filtratioRedBbluestdmatK3',...
    'filtratioRedGreenvarmatK1','filtratioRedGreenvarmatK2','filtratioRedGreenvarmatK3','filtratioRedGreenmeanmatK1',...
    'filtratioRedGreenmeanmatK2','filtratioRedGreenmeanmatK3','filtratioRedGreenmedianmatK1',...
    'filtratioRedGreenmedianmatK2','filtratioRedGreenmedianmatK3','filtratioRedGreenstdmat','filtratioRedGreenstdma2',...
    'filtratioRedGreenstdma3'};
description_periNuclei = {'mean value of periNuclei area', 'median of periNuclei area', 'variance of periNuclei area', 'standard deviation of periNuclei area', ...
    'mean value of periNuclei area to nuclei area ratio', 'mean value of periNuclei area to nuclei area ratio', 'mean value of periNuclei area to nuclei area ratio', 'mean value of periNuclei area to nuclei area ratio',...
    'Haralick:mean intensity angular_second_moment_energy','Haralick:standard deviation intensity angular_second_moment_energy',...
    'Haralick:mean intensity contrast_energy','Haralick:standard deviation intensity contrast_energy',...
    'Haralick:mean intensity correlation','Haralick:standard deviation intensity correlation',...
    'Haralick:mean intensity contrast_var','Haralick:standard deviation intensity contrast_var',...
    'Haralick:mean intensity inverse_difference_moment_homogeneity','Haralick:standard deviation intensity inverse_difference_moment_homogeneity',...
    'Haralick:mean intensity sum_average','Haralick:standard deviation intensity sum_average',...
    'Haralick:mean intensity sum_variance_aprox','Haralick:standard deviation intensity sum_variance_aprox',...
    'Haralick:mean intensity sum_entropy','Haralick:standard deviation intensity sum_entropy',...
    'Haralick:mean intensity entropy_cut_out_zeros','Haralick:standard deviation intensity entropy_cut_out_zeros',...
    'Haralick:mean intensity difference_variane,','Haralick:standard deviation intensity difference_variane,',...
    'Haralick:mean intensity difference_entropy','Haralick:standard deviation intensity difference_entropy',...
    'Haralick:mean intensity information_measure_of_correlation_I','Haralick:standard deviation intensity information_measure_of_correlation_I',...
    'Haralick:mean intensity information_measure_of_correlation_II','Haralick:standard deviation intensity information_measure_of_correlation_II',...
    'Haralick:mean intensity maximal_correlation_coefficient','Haralick:standard deviation intensity maximal_correlation_coefficient',...
    'entropy of periNuclei pixel intensity'};
description_spaTIL_v2 = {'NumClusters_G1'                                            ,...
'NumClusters_G2'                                            ,...
'TotalAreaClusters_G1'                                      ,...
'MeanAreaClusters_G1'                                       ,...
'StdAreaClusters_G1'                                        ,...
'MedianAreaClusters_G1'                                     ,...
'MaxAreaClusters_G1'                                        ,...
'MinAreaClusters_G1'                                        ,...
'KurtosisAreaClusters_G1'                                   ,...
'SkewnessAreaClusters_G1'                                   ,...
'TotalDensityClusters_G1'                                   ,...
'MeanDensityClusters_G1'                                    ,...
'StdDensityClusters_G1'                                     ,...
'MedianDensityClusters_G1'                                  ,...
'MaxDensityClusters_G1'                                     ,...
'MinDensityClusters_G1'                                     ,...
'KurtosisDensityClusters_G1'                                ,...
'SkewnessDensityClusters_G1'                                ,...
'TotalAreaClusters_G2'                                      ,...
'MeanAreaClusters_G2'                                       ,...
'StdAreaClusters_G2'                                        ,...
'MedianAreaClusters_G2'                                     ,...
'MaxAreaClusters_G2'                                        ,...
'MinAreaClusters_G2'                                        ,...
'KurtosisAreaClusters_G2'                                   ,...
'SkewnessAreaClusters_G2'                                   ,...
'TotalDensityClusters_G2'                                   ,...
'MeanDensityClusters_G2'                                    ,...
'StdDensityClusters_G2'                                     ,...
'MedianDensityClusters_G2'                                  ,...
'MaxDensityClusters_G2'                                     ,...
'MinDensityClusters_G2'                                     ,...
'KurtosisDensityClusters_G2'                                ,...
'SkewnessDensityClusters_G2'                                ,...
'TotalIntersectedAreaClusters_G1&2'                         ,...
'MeanIntersectedAreaClusters_G1&2'                          ,...
'StdIntersectedAreaClusters_G1&2'                           ,...
'MedianIntersectedAreaClusters_G1&2'                        ,...
'MaxIntersectedAreaClusters_G1&2'                           ,...
'MinIntersectedAreaClusters_G1&2'                           ,...
'KurtosisIntersectedAreaClusters_G1&2'                      ,...
'SkewnessIntersectedAreaClusters_G1&2'                      ,...
'TotalRatioIntersectedAreaClusters_G1&2_ToArea_G1'          ,...
'MeanRatioIntersectedAreaClusters_G1&2_ToArea_G1'           ,...
'StdRatioIntersectedAreaClusters_G1&2_ToArea_G1'            ,...
'MedianRatioIntersectedAreaClusters_G1&2_ToArea_G1'         ,...
'MaxRatioIntersectedAreaClusters_G1&2_ToArea_G1'            ,...
'MinRatioIntersectedAreaClusters_G1&2_ToArea_G1'            ,...
'KurtosisRatioIntersectedAreaClusters_G1&2_ToArea_G1'       ,...
'SkewnessRatioIntersectedAreaClusters_G1&2_ToArea_G1'       ,...
'TotalRatioIntersectedAreaClusters_G1&2_ToArea_G2'          ,...
'MeanRatioIntersectedAreaClusters_G1&2_ToArea_G2'           ,...
'StdRatioIntersectedAreaClusters_G1&2_ToArea_G2'            ,...
'MedianRatioIntersectedAreaClusters_G1&2_ToArea_G2'         ,...
'MaxRatioIntersectedAreaClusters_G1&2_ToArea_G2'            ,...
'MinRatioIntersectedAreaClusters_G1&2_ToArea_G2'            ,...
'KurtosisRatioIntersectedAreaClusters_G1&2_ToArea_G2'       ,...
'SkewnessRatioIntersectedAreaClusters_G1&2_ToArea_G2'       ,...
'TotalRatioIntersectedAreaClusters_G1&2_ToAvgArea_G1&2'     ,...
'MeanRatioIntersectedAreaClusters_G1&2_ToAvgArea_G1&2'      ,...
'StdRatioIntersectedAreaClusters_G1&2_ToAvgArea_G1&2'       ,...
'MedianRatioIntersectedAreaClusters_G1&2_ToAvgArea_G1&2'    ,...
'MaxRatioIntersectedAreaClusters_G1&2_ToAvgArea_G1&2'       ,...
'MinRatioIntersectedAreaClusters_G1&2_ToAvgArea_G1&2'       ,...
'KurtosisRatioIntersectedAreaClusters_G1&2_ToAvgArea_G1&2'  ,...
'SkewnessRatioIntersectedAreaClusters_G1&2_ToAvgArea_G1&2'  ,...
'TotalPercentageClusters_G1_Surrounding_G1_Neighborhood1'   ,...
'TotalPercentageClusters_G2_Surrounding_G1_Neighborhood1'   ,...
'TotalPercentageClusters_G1_Surrounding_G1_Neighborhood2'   ,...
'TotalPercentageClusters_G2_Surrounding_G1_Neighborhood2'   ,...
'TotalPercentageClusters_G1_Surrounding_G1_Neighborhood3'   ,...
'TotalPercentageClusters_G2_Surrounding_G1_Neighborhood3'   ,...
'TotalPercentageClusters_G1_Surrounding_G1_Neighborhood4'   ,...
'TotalPercentageClusters_G2_Surrounding_G1_Neighborhood4'   ,...
'TotalPercentageClusters_G1_Surrounding_G1_Neighborhood5'   ,...
'TotalPercentageClusters_G2_Surrounding_G1_Neighborhood5'   ,...
'MeanPercentageClusters_G1_Surrounding_G1_Neighborhood1'    ,...
'MeanPercentageClusters_G2_Surrounding_G1_Neighborhood1'    ,...
'MeanPercentageClusters_G1_Surrounding_G1_Neighborhood2'    ,...
'MeanPercentageClusters_G2_Surrounding_G1_Neighborhood2'    ,...
'MeanPercentageClusters_G1_Surrounding_G1_Neighborhood3'    ,...
'MeanPercentageClusters_G2_Surrounding_G1_Neighborhood3'    ,...
'MeanPercentageClusters_G1_Surrounding_G1_Neighborhood4'    ,...
'MeanPercentageClusters_G2_Surrounding_G1_Neighborhood4'    ,...
'MeanPercentageClusters_G1_Surrounding_G1_Neighborhood5'    ,...
'MeanPercentageClusters_G2_Surrounding_G1_Neighborhood5'    ,...
'StdPercentageClusters_G1_Surrounding_G1_Neighborhood1'     ,...
'StdPercentageClusters_G2_Surrounding_G1_Neighborhood1'     ,...
'StdPercentageClusters_G1_Surrounding_G1_Neighborhood2'     ,...
'StdPercentageClusters_G2_Surrounding_G1_Neighborhood2'     ,...
'StdPercentageClusters_G1_Surrounding_G1_Neighborhood3'     ,...
'StdPercentageClusters_G2_Surrounding_G1_Neighborhood3'     ,...
'StdPercentageClusters_G1_Surrounding_G1_Neighborhood4'     ,...
'StdPercentageClusters_G2_Surrounding_G1_Neighborhood4'     ,...
'StdPercentageClusters_G1_Surrounding_G1_Neighborhood5'     ,...
'StdPercentageClusters_G2_Surrounding_G1_Neighborhood5'     ,...
'MedianPercentageClusters_G1_Surrounding_G1_Neighborhood1'  ,...
'MedianPercentageClusters_G2_Surrounding_G1_Neighborhood1'  ,...
'MedianPercentageClusters_G1_Surrounding_G1_Neighborhood2'  ,...
'MedianPercentageClusters_G2_Surrounding_G1_Neighborhood2'  ,...
'MedianPercentageClusters_G1_Surrounding_G1_Neighborhood3'  ,...
'MedianPercentageClusters_G2_Surrounding_G1_Neighborhood3'  ,...
'MedianPercentageClusters_G1_Surrounding_G1_Neighborhood4'  ,...
'MedianPercentageClusters_G2_Surrounding_G1_Neighborhood4'  ,...
'MedianPercentageClusters_G1_Surrounding_G1_Neighborhood5'  ,...
'MedianPercentageClusters_G2_Surrounding_G1_Neighborhood5'  ,...
'MaxPercentageClusters_G1_Surrounding_G1_Neighborhood1'     ,...
'MaxPercentageClusters_G2_Surrounding_G1_Neighborhood1'     ,...
'MaxPercentageClusters_G1_Surrounding_G1_Neighborhood2'     ,...
'MaxPercentageClusters_G2_Surrounding_G1_Neighborhood2'     ,...
'MaxPercentageClusters_G1_Surrounding_G1_Neighborhood3'     ,...
'MaxPercentageClusters_G2_Surrounding_G1_Neighborhood3'     ,...
'MaxPercentageClusters_G1_Surrounding_G1_Neighborhood4'     ,...
'MaxPercentageClusters_G2_Surrounding_G1_Neighborhood4'     ,...
'MaxPercentageClusters_G1_Surrounding_G1_Neighborhood5'     ,...
'MaxPercentageClusters_G2_Surrounding_G1_Neighborhood5'     ,...
'MinPercentageClusters_G1_Surrounding_G1_Neighborhood1'     ,...
'MinPercentageClusters_G2_Surrounding_G1_Neighborhood1'     ,...
'MinPercentageClusters_G1_Surrounding_G1_Neighborhood2'     ,...
'MinPercentageClusters_G2_Surrounding_G1_Neighborhood2'     ,...
'MinPercentageClusters_G1_Surrounding_G1_Neighborhood3'     ,...
'MinPercentageClusters_G2_Surrounding_G1_Neighborhood3'     ,...
'MinPercentageClusters_G1_Surrounding_G1_Neighborhood4'     ,...
'MinPercentageClusters_G2_Surrounding_G1_Neighborhood4'     ,...
'MinPercentageClusters_G1_Surrounding_G1_Neighborhood5'     ,...
'MinPercentageClusters_G2_Surrounding_G1_Neighborhood5'     ,...
'KurtosisPercentageClusters_G1_Surrounding_G1_Neighborhood1',...
'KurtosisPercentageClusters_G2_Surrounding_G1_Neighborhood1',...
'KurtosisPercentageClusters_G1_Surrounding_G1_Neighborhood2',...
'KurtosisPercentageClusters_G2_Surrounding_G1_Neighborhood2',...
'KurtosisPercentageClusters_G1_Surrounding_G1_Neighborhood3',...
'KurtosisPercentageClusters_G2_Surrounding_G1_Neighborhood3',...
'KurtosisPercentageClusters_G1_Surrounding_G1_Neighborhood4',...
'KurtosisPercentageClusters_G2_Surrounding_G1_Neighborhood4',...
'KurtosisPercentageClusters_G1_Surrounding_G1_Neighborhood5',...
'KurtosisPercentageClusters_G2_Surrounding_G1_Neighborhood5',...
'SkewnessPercentageClusters_G1_Surrounding_G1_Neighborhood1',...
'SkewnessPercentageClusters_G2_Surrounding_G1_Neighborhood1',...
'SkewnessPercentageClusters_G1_Surrounding_G1_Neighborhood2',...
'SkewnessPercentageClusters_G2_Surrounding_G1_Neighborhood2',...
'SkewnessPercentageClusters_G1_Surrounding_G1_Neighborhood3',...
'SkewnessPercentageClusters_G2_Surrounding_G1_Neighborhood3',...
'SkewnessPercentageClusters_G1_Surrounding_G1_Neighborhood4',...
'SkewnessPercentageClusters_G2_Surrounding_G1_Neighborhood4',...
'SkewnessPercentageClusters_G1_Surrounding_G1_Neighborhood5',...
'SkewnessPercentageClusters_G2_Surrounding_G1_Neighborhood5',...
'TotalPercentageClusters_G1_Surrounding_G2_Neighborhood1'   ,...
'TotalPercentageClusters_G2_Surrounding_G2_Neighborhood1'   ,...
'TotalPercentageClusters_G1_Surrounding_G2_Neighborhood2'   ,...
'TotalPercentageClusters_G2_Surrounding_G2_Neighborhood2'   ,...
'TotalPercentageClusters_G1_Surrounding_G2_Neighborhood3'   ,...
'TotalPercentageClusters_G2_Surrounding_G2_Neighborhood3'   ,...
'TotalPercentageClusters_G1_Surrounding_G2_Neighborhood4'   ,...
'TotalPercentageClusters_G2_Surrounding_G2_Neighborhood4'   ,...
'TotalPercentageClusters_G1_Surrounding_G2_Neighborhood5'   ,...
'TotalPercentageClusters_G2_Surrounding_G2_Neighborhood5'   ,...
'MeanPercentageClusters_G1_Surrounding_G2_Neighborhood1'    ,...
'MeanPercentageClusters_G2_Surrounding_G2_Neighborhood1'    ,...
'MeanPercentageClusters_G1_Surrounding_G2_Neighborhood2'    ,...
'MeanPercentageClusters_G2_Surrounding_G2_Neighborhood2'    ,...
'MeanPercentageClusters_G1_Surrounding_G2_Neighborhood3'    ,...
'MeanPercentageClusters_G2_Surrounding_G2_Neighborhood3'    ,...
'MeanPercentageClusters_G1_Surrounding_G2_Neighborhood4'    ,...
'MeanPercentageClusters_G2_Surrounding_G2_Neighborhood4'    ,...
'MeanPercentageClusters_G1_Surrounding_G2_Neighborhood5'    ,...
'MeanPercentageClusters_G2_Surrounding_G2_Neighborhood5'    ,...
'StdPercentageClusters_G1_Surrounding_G2_Neighborhood1'     ,...
'StdPercentageClusters_G2_Surrounding_G2_Neighborhood1'     ,...
'StdPercentageClusters_G1_Surrounding_G2_Neighborhood2'     ,...
'StdPercentageClusters_G2_Surrounding_G2_Neighborhood2'     ,...
'StdPercentageClusters_G1_Surrounding_G2_Neighborhood3'     ,...
'StdPercentageClusters_G2_Surrounding_G2_Neighborhood3'     ,...
'StdPercentageClusters_G1_Surrounding_G2_Neighborhood4'     ,...
'StdPercentageClusters_G2_Surrounding_G2_Neighborhood4'     ,...
'StdPercentageClusters_G1_Surrounding_G2_Neighborhood5'     ,...
'StdPercentageClusters_G2_Surrounding_G2_Neighborhood5'     ,...
'MedianPercentageClusters_G1_Surrounding_G2_Neighborhood1'  ,...
'MedianPercentageClusters_G2_Surrounding_G2_Neighborhood1'  ,...
'MedianPercentageClusters_G1_Surrounding_G2_Neighborhood2'  ,...
'MedianPercentageClusters_G2_Surrounding_G2_Neighborhood2'  ,...
'MedianPercentageClusters_G1_Surrounding_G2_Neighborhood3'  ,...
'MedianPercentageClusters_G2_Surrounding_G2_Neighborhood3'  ,...
'MedianPercentageClusters_G1_Surrounding_G2_Neighborhood4'  ,...
'MedianPercentageClusters_G2_Surrounding_G2_Neighborhood4'  ,...
'MedianPercentageClusters_G1_Surrounding_G2_Neighborhood5'  ,...
'MedianPercentageClusters_G2_Surrounding_G2_Neighborhood5'  ,...
'MaxPercentageClusters_G1_Surrounding_G2_Neighborhood1'     ,...
'MaxPercentageClusters_G2_Surrounding_G2_Neighborhood1'     ,...
'MaxPercentageClusters_G1_Surrounding_G2_Neighborhood2'     ,...
'MaxPercentageClusters_G2_Surrounding_G2_Neighborhood2'     ,...
'MaxPercentageClusters_G1_Surrounding_G2_Neighborhood3'     ,...
'MaxPercentageClusters_G2_Surrounding_G2_Neighborhood3'     ,...
'MaxPercentageClusters_G1_Surrounding_G2_Neighborhood4'     ,...
'MaxPercentageClusters_G2_Surrounding_G2_Neighborhood4'     ,...
'MaxPercentageClusters_G1_Surrounding_G2_Neighborhood5'     ,...
'MaxPercentageClusters_G2_Surrounding_G2_Neighborhood5'     ,...
'MinPercentageClusters_G1_Surrounding_G2_Neighborhood1'     ,...
'MinPercentageClusters_G2_Surrounding_G2_Neighborhood1'     ,...
'MinPercentageClusters_G1_Surrounding_G2_Neighborhood2'     ,...
'MinPercentageClusters_G2_Surrounding_G2_Neighborhood2'     ,...
'MinPercentageClusters_G1_Surrounding_G2_Neighborhood3'     ,...
'MinPercentageClusters_G2_Surrounding_G2_Neighborhood3'     ,...
'MinPercentageClusters_G1_Surrounding_G2_Neighborhood4'     ,...
'MinPercentageClusters_G2_Surrounding_G2_Neighborhood4'     ,...
'MinPercentageClusters_G1_Surrounding_G2_Neighborhood5'     ,...
'MinPercentageClusters_G2_Surrounding_G2_Neighborhood5'     ,...
'KurtosisPercentageClusters_G1_Surrounding_G2_Neighborhood1',...
'KurtosisPercentageClusters_G2_Surrounding_G2_Neighborhood1',...
'KurtosisPercentageClusters_G1_Surrounding_G2_Neighborhood2',...
'KurtosisPercentageClusters_G2_Surrounding_G2_Neighborhood2',...
'KurtosisPercentageClusters_G1_Surrounding_G2_Neighborhood3',...
'KurtosisPercentageClusters_G2_Surrounding_G2_Neighborhood3',...
'KurtosisPercentageClusters_G1_Surrounding_G2_Neighborhood4',...
'KurtosisPercentageClusters_G2_Surrounding_G2_Neighborhood4',...
'KurtosisPercentageClusters_G1_Surrounding_G2_Neighborhood5',...
'KurtosisPercentageClusters_G2_Surrounding_G2_Neighborhood5',...
'SkewnessPercentageClusters_G1_Surrounding_G2_Neighborhood1',...
'SkewnessPercentageClusters_G2_Surrounding_G2_Neighborhood1',...
'SkewnessPercentageClusters_G1_Surrounding_G2_Neighborhood2',...
'SkewnessPercentageClusters_G2_Surrounding_G2_Neighborhood2',...
'SkewnessPercentageClusters_G1_Surrounding_G2_Neighborhood3',...
'SkewnessPercentageClusters_G2_Surrounding_G2_Neighborhood3',...
'SkewnessPercentageClusters_G1_Surrounding_G2_Neighborhood4',...
'SkewnessPercentageClusters_G2_Surrounding_G2_Neighborhood4',...
'SkewnessPercentageClusters_G1_Surrounding_G2_Neighborhood5',...
'SkewnessPercentageClusters_G2_Surrounding_G2_Neighborhood5',...
'GraphAreaStandardDeviation_G1'                             ,...
'GraphAreaAverage_G1'                                       ,...
'GraphAreaMinimum/Maximum_G1'                               ,...
'GraphAreaDisorder_G1'                                      ,...
'GraphPerimeterStandardDeviation_G1'                        ,...
'GraphPerimeterAverage_G1'                                  ,...
'GraphPerimeterMinimum/Maximum_G1'                          ,...
'GraphPerimeterDisorder_G1'                                 ,...
'GraphChordStandardDeviation_G1'                            ,...
'GraphChordAverage_G1'                                      ,...
'GraphChordMinimum/Maximum_G1'                              ,...
'GraphChordDisorder_G1'                                     ,...
'GraphSideLengthMinimum/Maximum_G1'                         ,...
'GraphSideLengthStandardDeviation_G1'                       ,...
'GraphSideLengthAverage_G1'                                 ,...
'GraphSideLengthDisorder_G1'                                ,...
'GraphTriangleAreaMinimum/Maximum_G1'                       ,...
'GraphTriangleAreaStandardDeviation_G1'                     ,...
'GraphTriangleAreaAverage_G1'                               ,...
'GraphTriangleAreaDisorder_G1'                              ,...
'GraphMSTEdgeLengthAverage_G1'                              ,...
'GraphMSTEdgeLengthStandardDeviation_G1'                    ,...
'GraphMSTEdgeLengthMinimum/Maximum_G1'                      ,...
'GraphMSTEdgeLengthDisorder_G1'                             ,...
'GraphAreaofpolygons_G1'                                    ,...
'GraphNumberofnuclei_G1'                                    ,...
'GraphDensityofNuclei_G1'                                   ,...
'GraphAveragedistanceto3NearestNeighbors_G1'                ,...
'GraphAveragedistanceto5NearestNeighbors_G1'                ,...
'GraphAveragedistanceto7NearestNeighbors_G1'                ,...
'GraphStandardDeviationdistanceto3NearestNeighbors_G1'      ,...
'GraphStandardDeviationdistanceto5NearestNeighbors_G1'      ,...
'GraphStandardDeviationdistanceto7NearestNeighbors_G1'      ,...
'GraphDisorderofdistanceto3NearestNeighbors_G1'             ,...
'GraphDisorderofdistanceto5NearestNeighbors_G1'             ,...
'GraphDisorderofdistanceto7NearestNeighbors_G1'             ,...
'GraphAvg.NearestNeighborsina10PixelRadius_G1'              ,...
'GraphAvg.NearestNeighborsina20PixelRadius_G1'              ,...
'GraphAvg.NearestNeighborsina30PixelRadius_G1'              ,...
'GraphAvg.NearestNeighborsina40PixelRadius_G1'              ,...
'GraphAvg.NearestNeighborsina50PixelRadius_G1'              ,...
'GraphStandardDeviationNearestNeighborsina10PixelRadius_G1' ,...
'GraphStandardDeviationNearestNeighborsina20PixelRadius_G1' ,...
'GraphStandardDeviationNearestNeighborsina30PixelRadius_G1' ,...
'GraphStandardDeviationNearestNeighborsina40PixelRadius_G1' ,...
'GraphStandardDeviationNearestNeighborsina50PixelRadius_G1' ,...
'GraphDisorderofNearestNeighborsina10PixelRadius_G1'        ,...
'GraphDisorderofNearestNeighborsina20PixelRadius_G1'        ,...
'GraphDisorderofNearestNeighborsina30PixelRadius_G1'        ,...
'GraphDisorderofNearestNeighborsina40PixelRadius_G1'        ,...
'GraphDisorderofNearestNeighborsina50PixelRadius_G1'        ,...
'GraphAreaStandardDeviation_G2'                             ,...
'GraphAreaAverage_G2'                                       ,...
'GraphAreaMinimum/Maximum_G2'                               ,...
'GraphAreaDisorder_G2'                                      ,...
'GraphPerimeterStandardDeviation_G2'                        ,...
'GraphPerimeterAverage_G2'                                  ,...
'GraphPerimeterMinimum/Maximum_G2'                          ,...
'GraphPerimeterDisorder_G2'                                 ,...
'GraphChordStandardDeviation_G2'                            ,...
'GraphChordAverage_G2'                                      ,...
'GraphChordMinimum/Maximum_G2'                              ,...
'GraphChordDisorder_G2'                                     ,...
'GraphSideLengthMinimum/Maximum_G2'                         ,...
'GraphSideLengthStandardDeviation_G2'                       ,...
'GraphSideLengthAverage_G2'                                 ,...
'GraphSideLengthDisorder_G2'                                ,...
'GraphTriangleAreaMinimum/Maximum_G2'                       ,...
'GraphTriangleAreaStandardDeviation_G2'                     ,...
'GraphTriangleAreaAverage_G2'                               ,...
'GraphTriangleAreaDisorder_G2'                              ,...
'GraphMSTEdgeLengthAverage_G2'                              ,...
'GraphMSTEdgeLengthStandardDeviation_G2'                    ,...
'GraphMSTEdgeLengthMinimum/Maximum_G2'                      ,...
'GraphMSTEdgeLengthDisorder_G2'                             ,...
'GraphAreaofpolygons_G2'                                    ,...
'GraphNumberofnuclei_G2'                                    ,...
'GraphDensityofNuclei_G2'                                   ,...
'GraphAveragedistanceto3NearestNeighbors_G2'                ,...
'GraphAveragedistanceto5NearestNeighbors_G2'                ,...
'GraphAveragedistanceto7NearestNeighbors_G2'                ,...
'GraphStandardDeviationdistanceto3NearestNeighbors_G2'      ,...
'GraphStandardDeviationdistanceto5NearestNeighbors_G2'      ,...
'GraphStandardDeviationdistanceto7NearestNeighbors_G2'      ,...
'GraphDisorderofdistanceto3NearestNeighbors_G2'             ,...
'GraphDisorderofdistanceto5NearestNeighbors_G2'             ,...
'GraphDisorderofdistanceto7NearestNeighbors_G2'             ,...
'GraphAvg.NearestNeighborsina10PixelRadius_G2'              ,...
'GraphAvg.NearestNeighborsina20PixelRadius_G2'              ,...
'GraphAvg.NearestNeighborsina30PixelRadius_G2'              ,...
'GraphAvg.NearestNeighborsina40PixelRadius_G2'              ,...
'GraphAvg.NearestNeighborsina50PixelRadius_G2'              ,...
'GraphStandardDeviationNearestNeighborsina10PixelRadius_G2' ,...
'GraphStandardDeviationNearestNeighborsina20PixelRadius_G2' ,...
'GraphStandardDeviationNearestNeighborsina30PixelRadius_G2' ,...
'GraphStandardDeviationNearestNeighborsina40PixelRadius_G2' ,...
'GraphStandardDeviationNearestNeighborsina50PixelRadius_G2' ,...
'GraphDisorderofNearestNeighborsina10PixelRadius_G2'        ,...
'GraphDisorderofNearestNeighborsina20PixelRadius_G2'        ,...
'GraphDisorderofNearestNeighborsina30PixelRadius_G2'        ,...
'GraphDisorderofNearestNeighborsina40PixelRadius_G2'        ,...
'GraphDisorderofNearestNeighborsina50PixelRadius_G2'        ,...
'IntersectionArea_G1&2'                                     ,...
'RatioIntersectedArea_G1&2_ToArea_G1'                       ,...
'RatioIntersectedArea_G1&2_ToArea_G2'                       ,...
'RatioIntersectedArea_G1&2_ToAvgArea_G1&2'                  ,...
'NumCentroidsClusters_G1_InConvHull_G2'                     ,...
'NumCentroidsClusters_G2_InConvHull_G1'                     ,...
'TotalGroupingFactor_G1'                                    ,...
'MeanGroupingFactor_G1'                                     ,...
'StdGroupingFactor_G1'                                      ,...
'MedianGroupingFactor_G1'                                   ,...
'MaxGroupingFactor_G1'                                      ,...
'MinGroupingFactor_G1'                                      ,...
'KurtosisGroupingFactor_G1'                                 ,...
'SkewnessGroupingFactor_G1'                                 ,...
'TotalGroupingFactor_G2'                                    ,...
'MeanGroupingFactor_G2'                                     ,...
'StdGroupingFactor_G2'                                      ,...
'MedianGroupingFactor_G2'                                   ,...
'MaxGroupingFactor_G2'                                      ,...
'MinGroupingFactor_G2'                                      ,...
'KurtosisGroupingFactor_G2'                                 ,...
'SkewnessGroupingFactor_G2'                                 };

save([folder_savepath 'histoTIL_feature_description.mat'],'description_nucFeat','description_denTIL','description_spaTIL','description_ctxTIL','description_periNuclei','description_spaTIL_v2');
end